"""initial schema

Revision ID: d6e8ba1cb465
Revises: 
Create Date: 2026-08-21 12:19:22.351676

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd6e8ba1cb465'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('datasets',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('detection_classes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('risk_weight', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('models',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('version', sa.String(length=100), nullable=False),
    sa.Column('task', sa.Enum('OBJECT_DETECTION', name='model_task'), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('organizations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dataset_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('split', sa.Enum('TRAIN', 'VALID', 'TEST', name='dataset_split'), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_images_dataset_id'), 'dataset_images', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_dataset_images_split'), 'dataset_images', ['split'], unique=False)
    op.create_table('model_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('model_id', sa.UUID(), nullable=False),
    sa.Column('dataset_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['dataset_id'], ['datasets.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['model_id'], ['models.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_model_runs_dataset_id'), 'model_runs', ['dataset_id'], unique=False)
    op.create_index(op.f('ix_model_runs_model_id'), 'model_runs', ['model_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'ANALYST', 'AGENT', 'OPERATOR', name='user_role'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_organization_id'), 'users', ['organization_id'], unique=False)
    op.create_table('complaints',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('reported_by', sa.UUID(), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('neighborhood', sa.String(length=255), nullable=True),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', 'CANCELED', name='complaint_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['reported_by'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaints_organization_id'), 'complaints', ['organization_id'], unique=False)
    op.create_index(op.f('ix_complaints_reported_by'), 'complaints', ['reported_by'], unique=False)
    op.create_index(op.f('ix_complaints_status'), 'complaints', ['status'], unique=False)
    op.create_table('dataset_annotations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('dataset_image_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('x_center', sa.Float(), nullable=False),
    sa.Column('y_center', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.CheckConstraint('height >= 0 AND height <= 1', name='ck_annotation_height'),
    sa.CheckConstraint('width >= 0 AND width <= 1', name='ck_annotation_width'),
    sa.CheckConstraint('x_center >= 0 AND x_center <= 1', name='ck_annotation_x_center'),
    sa.CheckConstraint('y_center >= 0 AND y_center <= 1', name='ck_annotation_y_center'),
    sa.ForeignKeyConstraint(['class_id'], ['detection_classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['dataset_image_id'], ['dataset_images.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_dataset_annotations_class_id'), 'dataset_annotations', ['class_id'], unique=False)
    op.create_index(op.f('ix_dataset_annotations_dataset_image_id'), 'dataset_annotations', ['dataset_image_id'], unique=False)
    op.create_table('missions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('complaint_id', sa.UUID(), nullable=False),
    sa.Column('pilot_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('altitude', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('status', sa.Enum('PLANNED', 'IN_PROGRESS', 'COMPLETED', 'CANCELED', name='mission_status'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['complaint_id'], ['complaints.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['pilot_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_missions_complaint_id'), 'missions', ['complaint_id'], unique=False)
    op.create_index(op.f('ix_missions_organization_id'), 'missions', ['organization_id'], unique=False)
    op.create_index(op.f('ix_missions_pilot_id'), 'missions', ['pilot_id'], unique=False)
    op.create_index(op.f('ix_missions_status'), 'missions', ['status'], unique=False)
    op.create_table('images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('filename', sa.String(length=500), nullable=False),
    sa.Column('path', sa.String(length=1000), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('altitude', sa.Float(), nullable=True),
    sa.Column('captured_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('processed', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_images_mission_id'), 'images', ['mission_id'], unique=False)
    op.create_index(op.f('ix_images_processed'), 'images', ['processed'], unique=False)
    op.create_table('reports',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('generated_by', sa.UUID(), nullable=False),
    sa.Column('file_path', sa.String(length=1000), nullable=False),
    sa.Column('generated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['generated_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reports_generated_by'), 'reports', ['generated_by'], unique=False)
    op.create_index(op.f('ix_reports_mission_id'), 'reports', ['mission_id'], unique=False)
    op.create_table('risk_areas',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mission_id', sa.UUID(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=False),
    sa.Column('longitude', sa.Float(), nullable=False),
    sa.Column('radius', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['mission_id'], ['missions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_risk_areas_mission_id'), 'risk_areas', ['mission_id'], unique=False)
    op.create_table('predictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('image_id', sa.UUID(), nullable=False),
    sa.Column('model_run_id', sa.UUID(), nullable=False),
    sa.Column('class_id', sa.UUID(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('x_center', sa.Float(), nullable=False),
    sa.Column('y_center', sa.Float(), nullable=False),
    sa.Column('width', sa.Float(), nullable=False),
    sa.Column('height', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('confidence >= 0 AND confidence <= 1', name='ck_prediction_confidence'),
    sa.CheckConstraint('height >= 0 AND height <= 1', name='ck_prediction_height'),
    sa.CheckConstraint('width >= 0 AND width <= 1', name='ck_prediction_width'),
    sa.CheckConstraint('x_center >= 0 AND x_center <= 1', name='ck_prediction_x_center'),
    sa.CheckConstraint('y_center >= 0 AND y_center <= 1', name='ck_prediction_y_center'),
    sa.ForeignKeyConstraint(['class_id'], ['detection_classes.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['image_id'], ['images.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['model_run_id'], ['model_runs.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_predictions_class_id'), 'predictions', ['class_id'], unique=False)
    op.create_index(op.f('ix_predictions_image_id'), 'predictions', ['image_id'], unique=False)
    op.create_index(op.f('ix_predictions_model_run_id'), 'predictions', ['model_run_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_predictions_model_run_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_image_id'), table_name='predictions')
    op.drop_index(op.f('ix_predictions_class_id'), table_name='predictions')
    op.drop_table('predictions')
    op.drop_index(op.f('ix_risk_areas_mission_id'), table_name='risk_areas')
    op.drop_table('risk_areas')
    op.drop_index(op.f('ix_reports_mission_id'), table_name='reports')
    op.drop_index(op.f('ix_reports_generated_by'), table_name='reports')
    op.drop_table('reports')
    op.drop_index(op.f('ix_images_processed'), table_name='images')
    op.drop_index(op.f('ix_images_mission_id'), table_name='images')
    op.drop_table('images')
    op.drop_index(op.f('ix_missions_status'), table_name='missions')
    op.drop_index(op.f('ix_missions_pilot_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_organization_id'), table_name='missions')
    op.drop_index(op.f('ix_missions_complaint_id'), table_name='missions')
    op.drop_table('missions')
    op.drop_index(op.f('ix_dataset_annotations_dataset_image_id'), table_name='dataset_annotations')
    op.drop_index(op.f('ix_dataset_annotations_class_id'), table_name='dataset_annotations')
    op.drop_table('dataset_annotations')
    op.drop_index(op.f('ix_complaints_status'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_reported_by'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_organization_id'), table_name='complaints')
    op.drop_table('complaints')
    op.drop_index(op.f('ix_users_organization_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_model_runs_model_id'), table_name='model_runs')
    op.drop_index(op.f('ix_model_runs_dataset_id'), table_name='model_runs')
    op.drop_table('model_runs')
    op.drop_index(op.f('ix_dataset_images_split'), table_name='dataset_images')
    op.drop_index(op.f('ix_dataset_images_dataset_id'), table_name='dataset_images')
    op.drop_table('dataset_images')
    op.drop_table('organizations')
    op.drop_table('models')
    op.drop_table('detection_classes')
    op.drop_table('datasets')
    # ### end Alembic commands ###
